# stage 1: python and packages
FROM python:3.13-slim AS pyenv

ARG POETRY_HOME=/opt/poetry

RUN python3 -m venv $POETRY_HOME \
    && $POETRY_HOME/bin/pip install poetry==2.2

COPY . /root/server/

RUN cd /root/server \
    && $POETRY_HOME/bin/poetry install --no-root \
    && $POETRY_HOME/bin/poetry build \
    && $POETRY_HOME/bin/poetry run python -m pip install dist/*.whl psutil

RUN cp -a /root/.cache/pypoetry/virtualenvs/*/lib/python3.13/site-packages/ /root/site-packages


# stage 2: main image
FROM gcr.io/distroless/python3-debian13:nonroot

COPY --from=pyenv /root/site-packages /home/nonroot/.local/lib/python3.13/site-packages

ENTRYPOINT ["/usr/bin/python3", "-m", "facmgr.client"]

