# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_server/server.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18grpc_server/server.proto\x12\x0f\x66\x61\x63torio_server\x1a\x1bgoogle/protobuf/empty.proto\"<\n\x0cSaveNameList\x12,\n\tsave_name\x18\x01 \x03(\x0b\x32\x19.factorio_server.SaveName\"\x18\n\x08SaveName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\x08SaveStat\x12\x11\n\tstat_json\x18\x01 \x01(\t\"d\n\rServerOptions\x12\x31\n\tsave_name\x18\x01 \x01(\x0b\x32\x19.factorio_server.SaveNameH\x00\x88\x01\x01\x12\x12\n\nextra_args\x18\x02 \x03(\tB\x0c\n\n_save_name\"\'\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf6\x02\n\rServerManager\x12G\n\x0eGetAllSaveName\x12\x16.google.protobuf.Empty\x1a\x1d.factorio_server.SaveNameList\x12\x45\n\rGetStatByName\x12\x19.factorio_server.SaveName\x1a\x19.factorio_server.SaveStat\x12=\n\nStopServer\x12\x16.google.protobuf.Empty\x1a\x17.factorio_server.Status\x12L\n\x11StartServerByName\x12\x1e.factorio_server.ServerOptions\x1a\x17.factorio_server.Status\x12H\n\rRestartServer\x12\x1e.factorio_server.ServerOptions\x1a\x17.factorio_server.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_server.server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SAVENAMELIST']._serialized_start=74
  _globals['_SAVENAMELIST']._serialized_end=134
  _globals['_SAVENAME']._serialized_start=136
  _globals['_SAVENAME']._serialized_end=160
  _globals['_SAVESTAT']._serialized_start=162
  _globals['_SAVESTAT']._serialized_end=191
  _globals['_SERVEROPTIONS']._serialized_start=193
  _globals['_SERVEROPTIONS']._serialized_end=293
  _globals['_STATUS']._serialized_start=295
  _globals['_STATUS']._serialized_end=334
  _globals['_SERVERMANAGER']._serialized_start=337
  _globals['_SERVERMANAGER']._serialized_end=711
# @@protoc_insertion_point(module_scope)
