name: Python package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        factorio-version: ["1.1.103", "1.1.104"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up environment
        run: |
          wget https://www.factorio.com/get-download/${{ matrix.factorio-version }}/headless/linux64 -O ~/factorio.tar.xz
          tar -xf ~/factorio.tar.xz -C ~
          ~/factorio/bin/x64/factorio --create ~/factorio/saves/test.zip
          pip install grpcio grpcio-tools
      - name: Run unittest
        run: |
          export executable=$(realpath -s ~/factorio/bin/x64/factorio)
          export savefile=$(realpath -s ~/factorio/saves/test.zip)
          python -m unittest tests.test_daemon.TestFactorioServerDaemon.test_start_stop
          python -m unittest tests.test_daemon.TestFactorioServerDaemon.test_restart
          python -m unittest tests.test_daemon.TestFactorioServerDaemon.test_get_message
          diff grpc_client/server.proto grpc_server/server.proto
